version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: stephenlautier/netcore-docker-ci:2.2.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
    steps:
      - run:
          name: Print environment versions
          command: |
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
            DOTNET_CLI_V=$(dotnet --version)
            echo dotnet cli version':' $DOTNET_CLI_V
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore
      - run:
          name: dotnet build
          command: dotnet build -c Release
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: nuget